name: CI/CD Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Snowflake CLI + dbt
        run: |
          pip install snowflake-cli-labs
          pip install dbt-snowflake

      - name: Write private key
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" > ~/.ssh/rsa_key.p8
          chmod 600 ~/.ssh/rsa_key.p8

      - name: Create Snowflake config
        run: |
          mkdir -p ~/.snowflake

          cat > ~/.snowflake/config.toml <<EOF
          default_connection_name = "devlop"

          [connections.devlop]
          account = "$SNOWFLAKE_ACCOUNT"
          user = "$SNOWFLAKE_USER"
          private_key_path = "/home/runner/.ssh/rsa_key.p8"
          authenticator = "SNOWFLAKE_JWT"
          warehouse = "$SNOWFLAKE_WAREHOUSE"
          database = "$SNOWFLAKE_DATABASE"
          schema = "$SNOWFLAKE_SCHEMA"
          role = "$SNOWFLAKE_ROLE"
          EOF

      - name: Test Snowflake connection
        run: snow connection test --connection devlop

      - name: Install dbt dependencies
        run: |
          cd cicd_demo
          dbt deps

      - name: dbt debug
        run: |
          cd cicd_demo
          dbt debug

      - name: dbt run
        run: |
          cd cicd_demo
          dbt run

      - name: dbt test
        run: |
          cd cicd_demo
          dbt test